### ISSUE TITLE
29. Use multi-stage builds to build Docker images for microservices

### ISSUE THREAD

**Issue by sergey-morenets** [ohanke/game_shop#149]

**Comment by michaltworuszka** [comment]
@sergey-morenets I have an Issue here

dockerfile:

FROM maven:3-openjdk-18 as maven

COPY pom.xml /opt/

WORKDIR /opt

RUN mvn dependency:resove

COPY . /opt/

RUN mvn install spring-boot:repackage

FROM openjdk

LABEL Author="Michał Tworuszka, Oskar Hanke, Paweł Manowski"

#ARG JAR_FILE=target/*.jar
COPY --from=maven  /opt/target/game_shop-notifications-0.0.1-SNAPSHOT.jar notifications.jar

WORKDIR /opt

ENTRYPOINT ["java","-jar","notifications.jar"]




But when I build it I have error:

 > [notifications maven 4/6] RUN mvn dependency:resove:
#0 1.459 [INFO] Scanning for projects...
#0 1.486 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
#0 1.486 [FATAL] Non-resolvable parent POM for org.springframework.boot:game_shop-notifications:0.0.1-SNAPSHOT: Could not find artifact org.springframework.boot:game_shop:pom:0.0.1-SNAPSHOT and 'parent.relativePath' points at wrong 
local POM @ line 5, column 13
#0 1.486  @
#0 1.488 [ERROR] The build could not read 1 project -> [Help 1]
#0 1.490 [ERROR]
#0 1.490 [ERROR]   The project org.springframework.boot:game_shop-notifications:0.0.1-SNAPSHOT (/opt/pom.xml) has 1 error
#0 1.491 [ERROR]     Non-resolvable parent POM for org.springframework.boot:game_shop-notifications:0.0.1-SNAPSHOT: Could not find artifact org.springframework.boot:game_shop:pom:0.0.1-SNAPSHOT and 'parent.relativePath' points at wr
ong local POM @ line 5, column 13 -> [Help 2]
#0 1.491 [ERROR]
#0 1.493 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#0 1.494 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#0 1.494 [ERROR]
#0 1.494 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#0 1.494 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
#0 1.494 [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
------
failed to solve: executor failed running [/bin/sh -c mvn dependency:resove]: exit code: 1





On Lectures you had the same error and you "deleted" from child pom parrent "dependency"

But can I do that? Because I have some dependencies and dependencie manager in Parrent pom.

**Comment by sergey-morenets** [comment]
Hi

Yes, in real-lfe project every microservice will be in the separate project (repository). But in our training project all the microservices are in the same project. So you need to copy the entire project to Docker image but build only the need sub-project (microservice).

**Comment by michaltworuszka** [comment]
I don't know if I understand. How can I in Dockerfile in single microservice copy the entire project to Docker image but build only the need sub-project (microservice)?

**Comment by sergey-morenets** [comment]
That's pretty simple and can be done in 3 steps in Dockerfile:
1) Copy entire project
2) Change current folder: WORKDIR sub-project1
3) mvn install spring-boot:repackage

**Comment by michaltworuszka** [comment]
But how can I copy entire project

Copy . ./ ?

**Comment by michaltworuszka** [comment]
And do I do this in every microservice Dockerfile - so every Dockerfile will copy entire project?

**Comment by michaltworuszka** [comment]
Ok so I create one Dockerfile at parent layer (same as docker-compose) and it will build all modules?

**Comment by sergey-morenets** [comment]
You will have one Dockerfile in the root folder, not in the every module. And yes, you don't need to delete Dockerfiles because they will not go to resulting jar file.
I recommend reviewing documentation about multi-stage build: https://docs.docker.com/develop/develop-images/multistage-build/
